#import "functions.typ": *
= Conclusions and Future Work <ch5>

This thesis has investigated the implementation and evaluation of a @LKA function inside a software-only @VIL simulation environment based on the CARLA simulator. The work spans the full chain from the selection of the simulation platform, through the modelling and the system identification of the vehicle, to the design of three progressively richer lateral-control architectures and to their numerical evaluation on a common test route. The present chapter summarizes the main findings of the previous chapters, restates the contributions of the work, and outlines the directions in which the present results could be extended.

== Summary of the Work
The thesis is articulated into four substantive chapters that build on each other in a clear progression from environment selection to controller evaluation.

@ch2 has selected CARLA as the simulation platform of the work, motivated by its open-source nature, its Unreal-Engine-4-based rendering, its accurate physics engine, and—most importantly for the present application—its comprehensive Python API. The same chapter has introduced the dynamic single-track bicycle model that underlies the controller design and has explained how the vehicle parameters $m, J, l_f, l_r, c_f, c_r$ have been read from the CARLA blueprint of the chosen `vehicle.nissan.patrol`. A dispatching procedure that converts the analytical longitudinal acceleration into the throttle/brake commands accepted by the simulator has been described, together with a dual-mode data-gathering pipeline—autopilot for reference paths, manual driving for edge cases—that produces the `.csv` files consumed by the controllers.

@ch3 has developed the lateral-control component of the @LKA function in three progressively richer architectures. The cross-track PID closes the loop on the perpendicular distance between the vehicle and a pre-recorded reference path; the corresponding plant is a double integrator and a full PID is required for stability. The heading-error PI closes the loop on the angle between the vehicle's forward direction and a look-ahead point on the same reference path; the corresponding plant is a single integrator and a PI controller is sufficient. The vision-based PI replaces the pre-recorded reference with a center line reconstructed at every tick from the RGB camera by the CLRNet lane detector @clrnet and by an inverse-perspective-mapping projection; the same PI controller of the heading-error formulation consumes the heading error computed in the body frame. A pole-placement procedure derives the PID gains analytically from a measurement of the steering gain $K_"steer"$ obtained by an open-loop step experiment on the simulator, and predicts that the heading-error formulation should be both more accurate, on a per-bandwidth basis, and more robust to changes in the vehicle speed.

@ch4 has evaluated the three architectures on a common test route in Town06. The numerical results have confirmed the predictions of the theoretical chapter on the relative ordering of the path-based controllers: the heading-error PI achieves an @RMSE of $0.120$ m and a maximum excursion of $1.185$ m against the $0.205$ m and $2.217$ m of the cross-track PID, an improvement by a factor of approximately $1.7$ on the average and of approximately $1.9$ on the worst case. The vision-based PI has achieved an @RMSE of $0.270$ m, which is larger than both path-based controllers; the increase is dominated by a steady-state bias of approximately $0.7$ m on the smooth curve, which has been traced back to two specific approximations of the perception layer—the geometric bias of the midline reconstruction and the first-degree polynomial fit of the center line. On a step-like lane discontinuity, the vision-based controller has been shown to react earlier than the path-based controllers and to produce the smoothest trajectory, at the cost of a large _apparent_ error against the discontinuous path-based reference.

== Contributions
The original contributions of this thesis can be summarized as follows.

#list(
    [A modular, software-only @VIL implementation of a @LKA function in the CARLA simulator, in which the controller runs as an external Python process and communicates with the simulator through the synchronous-mode Python API at $20$ Hz. The code is organized into three self-contained modules—`lane_shift_pid/`, `heading_error_pid/`, and the vision-based `detection&pid.py`—that share the same actuator, the same vehicle, and the same simulation rate, so that any observed difference between them can be attributed to the structure of the controller rather than to incidental implementation details. The complete source tree is publicly available in the open-source repository `LaneDetCarla` @lanedetcarla, which accompanies this thesis.],
    [A complete, reproducible system-identification procedure (`carla_sysid.py` and `pid_tuning.py`) that fits the parameters of a first-order longitudinal model and a one-parameter lateral steering gain from two open-loop step experiments, and derives analytical PID gains by pole placement on the resulting plants. The procedure is fully automatic and produces ready-to-use Python dictionaries for the controllers.],
    [A side-by-side comparison of three lateral-control architectures of increasing sophistication, including a detailed control-theoretic analysis (plant order, gain scheduling, phase margin) and a numerical evaluation on a common test route with two scalar metrics. The comparison isolates, for the first time in this specific simulation setup, the contribution of the perception layer from the contribution of the controller structure.],
    [A vision-based @LKA controller that combines a state-of-the-art lane-detection network @clrnet with an inverse-perspective-mapping projection and with the same heading-error PI of the path-based architecture. The vision-based controller is shown to be a viable @LKA implementation that does not require any pre-recorded reference path, at the cost of a steady-state bias on curves that has been quantitatively characterized.],
    [An explicit junction-handling logic that detects intersections through the CARLA waypoint graph and hands the control over to the Traffic Manager autopilot for the duration of the junction, with a clean reset of the PI controller state at every re-engagement. This makes it possible to run the vision-based @LKA on routes that include intersections, which would otherwise be unmanageable for a vision-only formulation.],
)

== Limitations
The work also has limitations that should be acknowledged.

The evaluation is restricted to a single vehicle, a single map (Town06) and a single target speed ($30$ km/h). The gain-scheduling analysis of @sec_heading predicts that the heading-error PI is robust to speed variations in the range $20$–$60$ km/h, but this prediction has not been verified experimentally; the same is true of the robustness to vehicle parameters. A systematic sweep over speed, vehicle and map would strengthen the generalizability of the results.

The reference path is recorded once with the CARLA autopilot, which is not guaranteed to be perfectly centered on the lane and which produces a step-like discontinuity at the lane-merge point of the route. This discontinuity has been kept on purpose, because it provides a stress test for the controllers, but a cleaner reference would allow a more direct quantitative comparison.

The perception layer is run in inference-only mode with the pre-trained CLRNet weights on the TuSimple dataset. The detector has not been fine-tuned on CARLA images, which produces a residual domain gap that contributes to the steady-state bias on curves. A simple data-collection and fine-tuning step on synthetic CARLA frames would likely reduce this bias.

The longitudinal controller is a simple PI on the speed and has not been the subject of a detailed analysis in this thesis. The cross-track and heading-error chapters have focused on the lateral channel; the coupling between the longitudinal and the lateral dynamics—for instance the effect of braking on the lateral acceleration during a tight turn—has been neglected.

Finally, the entire evaluation is performed in simulation and no real-vehicle test has been carried out. The Sim-to-Real gap is well known to introduce its own set of issues, in particular at the level of the perception layer, and the present results should be considered as indicative of the relative ordering of the three architectures rather than as quantitative predictions of their real-world performance.

== Future Work
Among the many directions in which the present work could be extended, the following three are the ones that the author considers most worth pursuing.

The first is the replacement of the reactive PI controllers with a _Model-Predictive Controller_ (MPC). All three architectures presented in this thesis close a feedback loop on a scalar error and react to its present value through a fixed control law; the rate saturation of the steering actuator then sets a hard limit on how aggressively the controllers can recover from a large transient, which is precisely what produces the worst-case excursions reported in @ch4 at the corner and at the lane discontinuity. An MPC that explicitly optimizes a finite-horizon cost on the lateral and heading errors, subject to the steering-rate constraint, would shape the transient in a control-theoretically optimal way rather than reacting to it. The bicycle model of @sec_bicycle is directly usable as the prediction model, and the system-identification procedure of @sec_sysid already provides the required parameters, so the prediction layer is essentially in place; what is missing is the optimization back-end and a careful tuning of the cost weights.

The second is the _fusion of the path-based and the vision-based references_ into a single look-ahead target. The two extremes have been characterized in detail in this thesis: the path-based controllers are accurate on the recorded route but require a pre-existing map, and the vision-based controller generalizes outside the recording but pays a steady-state bias on curves. An intermediate architecture that weighs the two sources by their respective covariances—a Kalman filter on the look-ahead point, or any equivalent multi-sensor fusion scheme—would inherit the accuracy of the path-based controllers where the map is reliable, and would fall back gracefully on the camera elsewhere. The same gains, the same metrics, and the same test route of @ch4 would carry over to the fused architecture, which makes it a natural follow-up rather than a complete rework.

The third, and most ambitious, is the _porting of the framework to a real research vehicle_. The path-based controllers require a localization module and a pre-recorded reference; the vision-based controller requires only the camera and the lane detector, and is therefore the most directly portable. A @VIL setup in the strict sense—real vehicle, virtual road generation, synchronized perception—as discussed in the literature review of @ch1, would be the natural intermediate step between the present pure-simulation evaluation and a fully on-road test. The Sim-to-Real gap on the perception layer is the main risk and would itself become a research topic; the control layer, having been derived analytically from a measured plant, should transfer with comparatively few surprises.

These three directions are listed in increasing order of ambition and of required infrastructure. The first two are largely software-only and could be carried out within the existing simulation framework; the third would require a substantial hardware effort and a multi-person team. Together they sketch a research programme that builds incrementally on the contributions of the present thesis.


== Closing Remarks
The work presented in this thesis has shown that a state-of-the-art driving simulator, an external Python control stack, and a deep-learning-based lane detector can be combined into a complete @LKA function that is amenable to rigorous control-theoretic analysis and to quantitative evaluation. The three architectures investigated cover the spectrum from a purely map-based controller to a purely vision-based one, and their side-by-side comparison clarifies the trade-offs that any practical @LKA system has to face: simplicity against accuracy, accuracy against generalization, generalization against robustness to perception failures. None of the three architectures dominates the others on every metric; each occupies a specific point in the design space and is appropriate for a specific deployment scenario. This kind of structured, simulation-based exploration of the design space is, in the view of the author, one of the most valuable contributions that a Vehicle-in-the-Loop methodology can bring to the development of autonomous driving systems.
